name: Node.js CI

on:
  push:
    branches: [ "**" ] # Jalan di semua branch
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma
      # Wajib agar build tidak error
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
      run: npx prisma generate

    - name: Build
      # Memasukkan semua secret yang sudah kamu buat di GitHub
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DIRECT_URL: ${{ secrets.DIRECT_URL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        PINECONE_INDEX_V2: ${{ secrets.PINECONE_INDEX_V2 }}
        LLAMAPARSE_API_KEY: ${{ secrets.LLAMAPARSE_API_KEY }}
        VOYAGEAI_API_KEY: ${{ secrets.VOYAGEAI_API_KEY }}
        MIDTRANS_SERVER_KEY: ${{ secrets.MIDTRANS_SERVER_KEY }}
        MIDTRANS_CLIENT_KEY: ${{ secrets.MIDTRANS_CLIENT_KEY }}
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${{ vars.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY }}
      run: npm run build --if-present

    # - run: npm test  <-- Aktifkan jika kamu punya file test (Jest/Vitest)
